version: '3.8'
services:
  zaviyaan-web:
    build: ./zaviyaan-web
    ports: ["8080:8080"]
    depends_on: [employee-service, inventory-service]
  employee-service:
    build: ./employee-service
    ports: ["8081:8081"]
  inventory-service:
    build: ./inventory-service
    ports: ["8082:8082"]
